#配置写库
write:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    #driverClass: com.mysql.jdbc.Driver 跟代码可知道DataSourceBuilder会自动根据url生成driverClassName
    # 最大连接数
    maxActive: 1000
    # 连接池初始化大小
    initialSize: 100
    # 获取连接的最大等待时间，单位毫秒
    maxWait: 60000
    # 最小保留数
    minIdle: 500
    # 检测关闭空闲连接的间隔时间，单位毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 连接的最小生存时间，，单位毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat, wall, slf4j
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true

#配置读库
read:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/read?useUnicode=true&characterEncoding=utf-8
    #driverClass: com.mysql.jdbc.Driver
    # 最大连接数
    maxActive: 1000
    # 连接池初始化大小
    initialSize: 100
    # 获取连接的最大等待时间，单位毫秒
    maxWait: 60000
    # 最小保留数
    minIdle: 500
    # 检测关闭空闲连接的间隔时间，单位毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 连接的最小生存时间，，单位毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat, wall, slf4j
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true